package output

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/pgulb/aimap/internal/symbol"
)

func TestRenderEmpty(t *testing.T) {
	dir := t.TempDir()
	outPath := filepath.Join(dir, "MAP.md")

	err := Render(nil, dir, outPath)
	if err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatal(err)
	}

	content := string(data)
	if !strings.Contains(content, "No symbols found") {
		t.Errorf("expected 'No symbols found', got: %s", content)
	}
	if !strings.Contains(content, "Symbol Map") {
		t.Error("expected 'Symbol Map' section heading")
	}
	if !strings.Contains(content, "GENERATED BY aimap") {
		t.Error("expected generated notice")
	}
}

func TestRenderPreservesExistingOverview(t *testing.T) {
	dir := t.TempDir()
	outPath := filepath.Join(dir, "MAP.md")

	initial := "# My Project\n\nSome architecture notes.\n\n<!-- SYMBOL MAP -->\n"
	if err := os.WriteFile(outPath, []byte(initial), 0644); err != nil {
		t.Fatal(err)
	}

	syms := []symbol.Symbol{
		{Name: "Foo", Kind: symbol.Function, FilePath: filepath.Join(dir, "main.go"), LineStart: 1, LineEnd: 5},
	}

	err := Render(syms, dir, outPath)
	if err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatal(err)
	}

	content := string(data)
	if !strings.Contains(content, "# My Project") {
		t.Error("expected original overview to be preserved")
	}
	if !strings.Contains(content, "Some architecture notes") {
		t.Error("expected architecture notes to be preserved")
	}
	if !strings.Contains(content, "`Foo`") {
		t.Error("expected Foo symbol in generated section")
	}
	if !strings.Contains(content, "main.go") {
		t.Error("expected relative path main.go")
	}
}

func TestRenderPathsAreRelative(t *testing.T) {
	dir := t.TempDir()
	outPath := filepath.Join(dir, "MAP.md")

	syms := []symbol.Symbol{
		{Name: "Greeting", Kind: symbol.Function, FilePath: filepath.Join(dir, "main.go"), LineStart: 1, LineEnd: 5},
		{Name: "Config", Kind: symbol.Struct, FilePath: filepath.Join(dir, "internal", "config.go"), LineStart: 7, LineEnd: 10},
		{Name: "main", Kind: symbol.Function, FilePath: filepath.Join(dir, "cmd", "aimap", "main.go"), LineStart: 20, LineEnd: 30},
	}

	err := Render(syms, dir, outPath)
	if err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatal(err)
	}

	content := string(data)
	if strings.Contains(content, dir) {
		t.Error("output should not contain absolute paths")
	}
	if !strings.Contains(content, "main.go") {
		t.Error("expected relative path main.go")
	}
	if !strings.Contains(content, "internal/config.go") {
		t.Error("expected relative path internal/config.go")
	}
	if !strings.Contains(content, "cmd/aimap/main.go") {
		t.Error("expected relative path cmd/aimap/main.go")
	}
}

func TestRenderGoSymbols(t *testing.T) {
	dir := t.TempDir()
	outPath := filepath.Join(dir, "MAP.md")

	syms := []symbol.Symbol{
		{Name: "Greeting", Kind: symbol.Function, FilePath: "/project/main.go", LineStart: 1, LineEnd: 5, Comment: "says hello"},
		{Name: "Config", Kind: symbol.Struct, FilePath: "/project/main.go", LineStart: 7, LineEnd: 10},
		{Name: "main", Kind: symbol.Function, FilePath: "/project/cmd/aimap/main.go", LineStart: 20, LineEnd: 30},
	}

	err := Render(syms, "/project", outPath)
	if err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatal(err)
	}

	content := string(data)

	if !strings.Contains(content, "Go Files") {
		t.Error("expected 'Go Files' section")
	}
	if !strings.Contains(content, "`Greeting`") {
		t.Error("expected Greeting symbol")
	}
	if !strings.Contains(content, "`Config`") {
		t.Error("expected Config symbol")
	}
	if !strings.Contains(content, "function") {
		t.Error("expected 'function' label")
	}
	if !strings.Contains(content, "struct") {
		t.Error("expected 'struct' label")
	}
	if !strings.Contains(content, "says hello") {
		t.Error("expected comment text")
	}
	if !strings.Contains(content, "main.go") {
		t.Error("expected relative path")
	}
}

func TestRenderPythonSymbols(t *testing.T) {
	dir := t.TempDir()
	outPath := filepath.Join(dir, "MAP.md")

	syms := []symbol.Symbol{
		{Name: "Config", Kind: symbol.Class, FilePath: "/project/app.py", LineStart: 1, LineEnd: 10},
		{Name: "get_name", Kind: symbol.Method, FilePath: "/project/app.py", LineStart: 5, LineEnd: 7, Parent: "Config"},
		{Name: "main", Kind: symbol.Function, FilePath: "/project/app.py", LineStart: 12, LineEnd: 15},
	}

	err := Render(syms, "/project", outPath)
	if err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatal(err)
	}

	content := string(data)
	if !strings.Contains(content, "Python Files") {
		t.Error("expected 'Python Files' section")
	}
	if !strings.Contains(content, "`Config`") {
		t.Error("expected Config symbol")
	}
	if !strings.Contains(content, "`Config.get_name`") {
		t.Error("expected Config.get_name method notation")
	}
	if !strings.Contains(content, "`main`") {
		t.Error("expected main symbol")
	}
	if !strings.Contains(content, "class") {
		t.Error("expected 'class' label")
	}
}

func TestRenderLineRanges(t *testing.T) {
	dir := t.TempDir()
	outPath := filepath.Join(dir, "MAP.md")

	syms := []symbol.Symbol{
		{Name: "Foo", Kind: symbol.Function, FilePath: "/project/f.go", LineStart: 1, LineEnd: 1},
		{Name: "Bar", Kind: symbol.Function, FilePath: "/project/f.go", LineStart: 3, LineEnd: 10},
	}

	err := Render(syms, "/project", outPath)
	if err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatal(err)
	}

	content := string(data)
	if !strings.Contains(content, "(line 1)") {
		t.Error("expected single-line range notation")
	}
	if !strings.Contains(content, "(lines 3-10)") {
		t.Error("expected multi-line range notation")
	}
}

func TestKindLabel(t *testing.T) {
	tests := []struct {
		kind symbol.SymbolKind
		want string
	}{
		{symbol.Function, "function"},
		{symbol.Method, "method"},
		{symbol.Struct, "struct"},
		{symbol.Interface, "interface"},
		{symbol.Type, "type"},
		{symbol.Variable, "variable"},
		{symbol.Constant, "constant"},
		{symbol.Class, "class"},
	}

	for _, tt := range tests {
		got := kindLabel(tt.kind)
		if got != tt.want {
			t.Errorf("kindLabel(%v) = %q, want %q", tt.kind, got, tt.want)
		}
	}
}
