package output

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/pgulb/aimap/internal/symbol"
)

const marker = "<!-- SYMBOL MAP -->"

const generatedNotice = "<!-- GENERATED BY aimap. The symbol map section below is auto-generated. Do not edit manually. -->"

func kindLabel(k symbol.SymbolKind) string {
	switch k {
	case symbol.Function:
		return "function"
	case symbol.Method:
		return "method"
	case symbol.Struct:
		return "struct"
	case symbol.Interface:
		return "interface"
	case symbol.Type:
		return "type"
	case symbol.Variable:
		return "variable"
	case symbol.Constant:
		return "constant"
	case symbol.Class:
		return "class"
	default:
		return "symbol"
	}
}

// Render writes symbols to the specified output path as a markdown file.
// root is the absolute project root — used to relativize file paths in the output.
// If the output file already exists and contains the marker comment,
// everything before the marker is preserved as the architectural overview.
// The marker and everything after it is replaced with the symbol listing.
func Render(symbols []symbol.Symbol, root, outputPath string) error {
	var preamble string

	if existing, err := os.ReadFile(outputPath); err == nil {
		content := string(existing)
		if idx := strings.Index(content, marker); idx >= 0 {
			preamble = content[:idx+len(marker)] + "\n\n"
		}
	}

	if preamble == "" {
		preamble = generatedNotice + "\n\n# Project Map\n\n"
		if !strings.Contains(preamble, marker) {
			preamble += marker + "\n\n"
		}
	}

	var b strings.Builder
	b.WriteString(preamble)
	b.WriteString("## Symbol Map\n\n")

	if len(symbols) == 0 {
		b.WriteString("No symbols found.\n")
		return os.WriteFile(outputPath, []byte(b.String()), 0644)
	}

	byFile := make(map[string][]symbol.Symbol)
	for _, s := range symbols {
		byFile[s.FilePath] = append(byFile[s.FilePath], s)
	}

	var filePaths []string
	for p := range byFile {
		filePaths = append(filePaths, p)
	}
	sort.Strings(filePaths)

	sections := []struct {
		label string
		files []string
	}{
		{"Go Files", nil},
		{"Python Files", nil},
		{"Other Files", nil},
	}

	for _, p := range filePaths {
		ext := strings.ToLower(filepath.Ext(p))
		switch ext {
		case ".go":
			sections[0].files = append(sections[0].files, p)
		case ".py":
			sections[1].files = append(sections[1].files, p)
		default:
			sections[2].files = append(sections[2].files, p)
		}
	}

	for _, sec := range sections {
		if len(sec.files) == 0 {
			continue
		}
		b.WriteString(fmt.Sprintf("### %s\n\n", sec.label))

		for _, p := range sec.files {
			syms := byFile[p]

			displayPath := relativize(root, p)
			b.WriteString(fmt.Sprintf("#### %s\n\n", displayPath))

			sort.Slice(syms, func(i, j int) bool {
				if syms[i].LineStart != syms[j].LineStart {
					return syms[i].LineStart < syms[j].LineStart
				}
				return syms[i].Name < syms[j].Name
			})

			for _, s := range syms {
				label := kindLabel(s.Kind)
				lineRange := formatLineRange(s.LineStart, s.LineEnd)
				name := s.Name

				if s.Parent != "" {
					name = fmt.Sprintf("%s.%s", s.Parent, name)
				}

				b.WriteString(fmt.Sprintf("- `%s` — %s %s", name, label, lineRange))

				if s.Comment != "" {
					commentLine := strings.SplitN(s.Comment, "\n", 2)[0]
					b.WriteString(fmt.Sprintf(" — %s", commentLine))
				}

				b.WriteString("\n")
			}
			b.WriteString("\n")
		}
	}

	return os.WriteFile(outputPath, []byte(b.String()), 0644)
}

func relativize(root, absPath string) string {
	rel, err := filepath.Rel(root, absPath)
	if err != nil {
		return filepath.Base(absPath)
	}
	return filepath.ToSlash(rel)
}

func formatLineRange(start, end int) string {
	if start == end {
		return fmt.Sprintf("(line %d)", start)
	}
	return fmt.Sprintf("(lines %d-%d)", start, end)
}
